const IMG='./assets/exercises/';
const FEMALE_IMG='./assets/female/';
const base=[
['deep-squat','Tiefe Hocke','Deep Squat','01-deep-squat.webp','ankle','Beginner'],['couch','Couch Stretch','Couch Stretch','02-couch-stretch.webp','hip','Beginner'],['cat-cow','Katze–Kuh','Cat–Cow','03-cat-cow.webp','spine','Beginner'],['bridge','Glute Bridge','Glute Bridge','04-glute-bridge.webp','hip','Beginner'],['dead-bug','Dead Bug','Dead Bug','05-dead-bug.webp','core','Beginner'],['side-plank','Seitstütz','Side Plank','06-side-plank.webp','core','Intermediate'],['hip-switch','90/90 Hüftwechsel','90/90 Hip Switch','07-hip-switch.webp','hip','Beginner'],['wgs','World’s Greatest Stretch','World’s Greatest Stretch','08-worlds-greatest-stretch.webp','full','Intermediate'],['thoracic','BWS-Rotation','Thoracic Rotation','09-thoracic-rotation.webp','spine','Beginner'],['ham-sweep','Hamstring Sweep','Hamstring Sweep','10-hamstring-sweep.webp','hamstring','Beginner'],['lunge-twist','Ausfallschritt + Rotation','Lunge with Twist','11-lunge-with-twist.webp','full','Intermediate']];
const extras=[
['frog','Frog Stretch','Frog Stretch','07-hip-switch.webp','adductor','Intermediate'],['butterfly','Schmetterling','Butterfly','07-hip-switch.webp','adductor','Beginner'],['cossack','Cossack Squat','Cossack Squat','01-deep-squat.webp','adductor','Intermediate'],['pancake','Pancake Hold','Pancake Hold','10-hamstring-sweep.webp','hamstring','Advanced'],['elephant','Elephant Walk','Elephant Walk','10-hamstring-sweep.webp','hamstring','Beginner'],['pike','Pike Compression','Pike Compression','05-dead-bug.webp','hamstring','Advanced'],['split-prep','Front-Split Vorbereitung','Front Split Prep','02-couch-stretch.webp','hip','Intermediate'],['split-slide','Front-Split Slides','Front Split Slides','02-couch-stretch.webp','hip','Advanced'],['middle-prep','Middle-Split Vorbereitung','Middle Split Prep','07-hip-switch.webp','adductor','Intermediate'],['middle-hold','Middle-Split Hold','Middle Split Hold','01-deep-squat.webp','adductor','Advanced'],['ankle-rock','Sprunggelenk Rocks','Ankle Rocks','01-deep-squat.webp','ankle','Beginner'],['calf','Waden-Stretch','Calf Stretch','02-couch-stretch.webp','ankle','Beginner'],['tibialis','Tibialis Raise','Tibialis Raise','01-deep-squat.webp','ankle','Intermediate'],['wall-slide','Wall Slides','Wall Slides','09-thoracic-rotation.webp','shoulder','Beginner'],['shoulder-cars','Schulter CARs','Shoulder CARs','09-thoracic-rotation.webp','shoulder','Intermediate'],['hang','Aktiver Hang','Active Hang','06-side-plank.webp','shoulder','Intermediate'],['handstand-line','Handstand Line Drill','Handstand Line Drill','06-side-plank.webp','shoulder','Advanced'],['cobra','Cobra Flow','Cobra Flow','03-cat-cow.webp','spine','Beginner'],['bridge-prep','Bridge Prep','Bridge Prep','04-glute-bridge.webp','spine','Advanced'],['thread','Thread the Needle','Thread the Needle','09-thoracic-rotation.webp','spine','Beginner']];
const exercises=[...base,...extras].map((x,i)=>({id:x[0],de:x[1],en:x[2],img:x[3],area:x[4],level:x[5],sec:i%3===0?45:i%3===1?40:30,tips:['Ruhig und kontrolliert bewegen','Niemals in stechenden Schmerz gehen','Gleichmäßig durch die Nase atmen']}));
const goals={front:{de:'Front Split',en:'Front Split',desc:'Vollständiger Längsspagat mit kontrolliertem Becken.',areas:['hip','hamstring','core']},middle:{de:'Middle Split',en:'Middle Split',desc:'Seitlicher Spagat mit aktiver Adduktorenkontrolle.',areas:['adductor','hip','core']},pancake:{de:'Pancake',en:'Pancake',desc:'Tiefe Vorbeuge aus der Grätsche mit langem Rücken.',areas:['hamstring','adductor','spine']},squat:{de:'Deep Squat',en:'Deep Squat',desc:'Stabile tiefe Hocke mit aufrechtem Oberkörper.',areas:['ankle','hip','spine']},overhead:{de:'Overhead Freedom',en:'Overhead Freedom',desc:'Freie Schulterbewegung für Handstand und Krafttraining.',areas:['shoulder','spine','core']}};
const defaults={lang:'de',sex:'male',level:'Beginner',goal:'front',name:'',onboarded:false,music:true,volume:.22,effectsVolume:.75,sound:'softBell',countdownSound:true,vibration:true,sessions:0,streak:0,score:0,xp:0,dailyDone:false,lastSessionSeconds:0,lastSessionExercises:0,lastAssessment:0};
let S={...defaults,...JSON.parse(localStorage.getItem('stas3')||'{}')};
let player={queue:[],index:0,phase:'idle',left:0,total:0,running:false,raf:0,last:0,count:3};
let audio={ctx:null,master:null,osc:[],on:false};
const app=document.querySelector('#app'); const tr=(de,en)=>S.lang==='de'?de:en; const exn=e=>S.lang==='de'?e.de:e.en;
function imageFor(e){
  const exactMale={
    bridge:'./assets/male/male-glute-bridge.webp',
    frog:'./assets/male/male-frog-stretch.webp',
    'hip-switch':'./assets/male/male-pigeon-stretch.webp',
    couch:'./assets/male/male-lunge-stretch.webp',
    'split-prep':'./assets/male/male-front-split.webp',
    'split-slide':'./assets/male/male-front-split.webp'
  };
  const exactFemale={
    bridge:'./assets/female/female-glute-bridge.webp',
    frog:'./assets/female/female-frog-stretch.webp',
    'hip-switch':'./assets/female/female-pigeon-stretch.webp',
    couch:'./assets/female/female-lunge-stretch.webp',
    'split-prep':'./assets/female/female-front-split.webp',
    'split-slide':'./assets/female/female-front-split.webp',
    pancake:'./assets/female/female-front-split.webp'
  };
  if(S.sex==='female'){
    if(exactFemale[e.id])return exactFemale[e.id];
    const femaleFallback={hip:'female-pigeon-stretch.webp',hamstring:'female-front-split.webp',adductor:'female-frog-stretch.webp',ankle:'female-lunge-stretch.webp',shoulder:'female-pigeon-stretch.webp',spine:'female-pigeon-stretch.webp',core:'female-glute-bridge.webp',full:'female-lunge-stretch.webp'};
    return './assets/female/'+(femaleFallback[e.area]||'female-pigeon-stretch.webp');
  }
  return exactMale[e.id]||IMG+e.img;
}
function goalTitle(key){const g=goals[key];if(key==='front')return S.sex==='female'?tr('Frauen-Spagat · Front Split','Women’s Split · Front Split'):tr('Männer-Spagat · Front Split','Men’s Split · Front Split');if(key==='middle')return S.sex==='female'?tr('Frauen-Spagat · Seitspagat','Women’s Split · Middle Split'):tr('Männer-Spagat · Seitspagat','Men’s Split · Middle Split');return g[S.lang]}
function goalDesc(key){const g=goals[key];if(key==='front')return S.sex==='female'?tr('Finalziel: kontrollierter Längsspagat mit stabilem Becken.','Final goal: controlled front split with a stable pelvis.'):tr('Finalziel: kraftvoller Längsspagat mit aktiver Hüftkontrolle.','Final goal: strong front split with active hip control.');if(key==='middle')return tr('Finalziel: vollständiger Seitspagat mit aktiver Adduktorenkontrolle.','Final goal: full middle split with active adductor control.');return g.desc}
function save(){localStorage.setItem('stas3',JSON.stringify(S))} function set(p){Object.assign(S,p);save();render()}
function icon(x){return `<span class="ico">${x}</span>`}
function nav(active='start'){return `<nav class="nav">${[['start','⌂',tr('Start','Start')],['plan','▤',tr('Plan','Plan')],['library','▦',tr('Übungen','Library')],['progress','◔',tr('Fortschritt','Progress')],['profile','⚙',tr('Einstellungen','Settings')]].map(x=>`<button data-go="${x[0]}" class="${active===x[0]?'active':''}">${icon(x[1])}${x[2]}</button>`).join('')}</nav>`}
function shell(body,active='home'){return `<div class="shell"><header><div class="logo">STAS<span>THE ARCHITECTURE OF THE BODY</span></div><button class="chip" data-lang>${S.lang.toUpperCase()}</button></header><main>${body}</main>${nav(active)}</div>`}
function goHome(){player.running=false;cancelAnimationFrame(player.raf);stopAudio();history.replaceState(null,'',location.pathname+location.search+'#start');startPage()}
function render(){const hash=location.hash.slice(1)||'start'; if(hash==='session'&&!player.queue.length){return goHome()} if(hash==='session')return sessionView(); if(hash==='dashboard')return home(); if(hash==='plan')return planView(); if(hash==='library')return library(); if(hash==='progress')return progress(); if(hash==='profile')return profile(); startPage()}

function startPage(){
  const goalButtons=Object.entries(goals).map(([k,g])=>`<button data-goal="${k}" class="goal ${S.goal===k?'sel':''}"><strong>${goalTitle(k)}</strong><span>${goalDesc(k)}</span></button>`).join('');
  app.innerHTML=shell(`<section class="entry-hero"><div><p class="kicker">STAS · THE ARCHITECTURE OF THE BODY</p><h1>${tr('Dein persönlicher Einstieg','Your personal starting point')}</h1><p>${tr('Wähle Modell, Level und finales Ziel. Diese Seite ist für jede neue Person sofort erreichbar.','Choose model, level and final goal. This page is immediately available for every new person.')}</p></div><button class="chip" data-lang>${S.lang.toUpperCase()}</button></section><section class="entry-panel"><div class="entry-step"><span>01</span><div><p class="kicker">${tr('MODELL','MODEL')}</p><h2>${tr('Wer trainiert?','Who is training?')}</h2></div></div><div class="choice-grid"><button class="choice ${S.sex==='male'?'sel':''}" data-sex="male"><b>♂</b><strong>${tr('Männlich','Male')}</strong><span>${tr('Männliche Bildwelt','Male imagery')}</span></button><button class="choice ${S.sex==='female'?'sel':''}" data-sex="female"><b>♀</b><strong>${tr('Weiblich','Female')}</strong><span>${tr('Weibliche Bildwelt','Female imagery')}</span></button></div><div class="entry-step"><span>02</span><div><p class="kicker">LEVEL</p><h2>${tr('Trainingsniveau','Training level')}</h2></div></div><div class="level-list compact">${['Beginner','Intermediate','Advanced','Elite'].map((l,i)=>`<button data-level="${l}" class="${S.level===l?'sel':''}"><b>${String(i+1).padStart(2,'0')}</b><span><strong>${l}</strong><small>${[tr('Grundlagen','Fundamentals'),tr('Aufbau','Development'),tr('Fortgeschritten','Advanced'),tr('Profi','Professional')][i]}</small></span></button>`).join('')}</div><div class="entry-step"><span>03</span><div><p class="kicker">FINAL GOAL</p><h2>${tr('Finales Ziel auswählen','Choose final goal')}</h2></div></div><div class="goal-grid">${goalButtons}</div><div class="entry-actions"><button class="btn gold" data-enter>${tr('Profil starten','Start profile')} →</button>${S.onboarded?`<button class="btn ghost" data-dashboard>${tr('Zum bestehenden Dashboard','Open existing dashboard')}</button>`:''}</div></section>`, 'start')
}
function onboard(step=Number(sessionStorage.getItem('obStep')||0)){const steps=[
`<div class="ob-hero"><img src="./assets/hero.webp"><div><p class="kicker">STAS 3.0</p><h1>${tr('Dein Körper. Strukturiert entwickelt.','Your body. Engineered.')}</h1><p>${tr('Ein personalisiertes Mobility-System mit Assessment, Zielpfad und geführten Sessions.','A personalized mobility system with assessment, goal paths and guided sessions.')}</p></div></div>`,
`<p class="kicker">01 / 03</p><h1>${tr('Wähle dein Modell','Choose your model')}</h1><div class="choice-grid"><button class="choice ${S.sex==='male'?'sel':''}" data-sex="male"><b>♂</b><strong>${tr('Männlich','Male')}</strong><span>${tr('Performance & Kraft','Performance & strength')}</span></button><button class="choice ${S.sex==='female'?'sel':''}" data-sex="female"><b>♀</b><strong>${tr('Weiblich','Female')}</strong><span>${tr('Flexibility & Control','Flexibility & control')}</span></button></div><p class="notice">${tr('Das Modell steuert die Bilddarstellung. Die Trainingslogik basiert auf deinem Level und Ziel.','The model controls imagery. Training logic is based on level and goal.')}</p>`,
`<p class="kicker">02 / 03</p><h1>${tr('Dein Trainingslevel','Your training level')}</h1><div class="level-list">${['Beginner','Intermediate','Advanced','Elite'].map((l,i)=>`<button data-level="${l}" class="${S.level===l?'sel':''}"><b>${['01','02','03','04'][i]}</b><span><strong>${l}</strong><small>${[tr('Basisbeweglichkeit aufbauen','Build mobility fundamentals'),tr('Kontrolle und Bewegungsumfang','Control and range'),tr('Intensive Endpositionen','Intense end ranges'),tr('Athletische Spezialisierung','Athletic specialization')][i]}</small></span></button>`).join('')}</div>`,
`<p class="kicker">03 / 03</p><h1>${tr('Wähle dein finales Ziel','Choose your final goal')}</h1><div class="goal-grid">${Object.entries(goals).map(([k,g])=>`<button data-goal="${k}" class="goal ${S.goal===k?'sel':''}"><strong>${goalTitle(k)}</strong><span>${goalDesc(k)}</span></button>`).join('')}</div>`];
app.innerHTML=`<div class="onboarding"><div class="ob-card">${steps[step]}<div class="ob-actions">${step?`<button class="btn ghost" data-ob-prev>${tr('Zurück','Back')}</button>`:''}<button class="btn gold" data-ob-next>${step===3?tr('Plan erstellen','Create plan'):tr('Weiter','Continue')}</button></div></div></div>`}
function buildPlan(){const rank={Beginner:0,Intermediate:1,Advanced:2,Elite:3}[S.level], allowed=['Beginner','Intermediate','Advanced','Elite'].slice(0,rank+1);let list=exercises.filter(e=>allowed.includes(e.level));const target=goals[S.goal].areas;list.sort((a,b)=>target.includes(b.area)-target.includes(a.area));const count=[8,10,12,14][rank];return list.slice(0,count)}
function backHeader(title){return `<div class="page-head"><button class="back-btn" data-back aria-label="${tr('Zurück','Back')}">←</button><div><p class="kicker">STAS 4.0</p><h1>${title}</h1></div><button class="home-btn" data-go="start" aria-label="Dashboard">⌂</button></div>`}

function areaScores(){const offsets={shoulder:7,spine:1,hip:10,hamstring:-8,adductor:-4,ankle:-2,core:8};const focus=goals[S.goal].areas;return Object.fromEntries(Object.keys(offsets).map(k=>[k,Math.max(12,Math.min(100,S.score+offsets[k]+(focus.includes(k)?6:0)))]))}
function grade(v){return v>=85?'A+':v>=75?'A':v>=65?'B':v>=50?'C':'D'}
function xpLevel(){const n=Math.floor(S.xp/100)+1;const names=[tr('Explorer','Explorer'),tr('Builder','Builder'),tr('Athlete','Athlete'),tr('Performer','Performer'),tr('Elite','Elite'),tr('Master','Master')];return {n,name:names[Math.min(names.length-1,Math.floor((n-1)/4))],pct:S.xp%100}}
function coach(){const a=areaScores(),sorted=Object.entries(a).sort((x,y)=>x[1]-y[1]),weak=sorted[0][0],strong=sorted.at(-1)[0];const names={shoulder:tr('Schultern','shoulders'),spine:tr('Wirbelsäule','spine'),hip:tr('Hüfte','hips'),hamstring:'Hamstrings',adductor:tr('Adduktoren','adductors'),ankle:tr('Sprunggelenke','ankles'),core:'Core'};return `<section class="coach-card"><div class="coach-orb">✦</div><div><p class="kicker">STAS SMART COACH</p><h2>${tr('Dein nächster Hebel','Your next leverage point')}</h2><p>${tr(`Deine ${names[strong]} entwickeln sich stabil. Der größte Engpass liegt aktuell bei ${names[weak]}. Der nächste Plan priorisiert diesen Bereich, ohne dein Finalziel aus dem Fokus zu verlieren.`,`Your ${names[strong]} are progressing steadily. Your largest current restriction is ${names[weak]}. The next plan prioritizes it without losing focus on your final goal.`)}</p></div></section>`}
function mobilityDNA(){const a=areaScores(),items=[['shoulder',tr('Schulter','Shoulder')],['hip',tr('Hüfte','Hips')],['hamstring','Hamstrings'],['ankle',tr('Sprunggelenk','Ankle')],['spine',tr('Wirbelsäule','Spine')],['core','Core']];return `<section class="dna-card"><div><p class="kicker">MOBILITY DNA</p><h2>${tr('Dein Bewegungsprofil','Your movement profile')}</h2><p>${tr('Aus Assessment, Zielpfad und Trainingshistorie berechnet.','Calculated from assessment, goal path and training history.')}</p></div><div class="dna-grid">${items.map(([k,n])=>`<span><small>${n}</small><b>${grade(a[k])}</b><i style="--v:${a[k]}"></i></span>`).join('')}</div></section>`}
function journey(){const milestones={front:[tr('Knie gestreckt','Straight knees'),tr('Hände am Boden','Hands to floor'),tr('20 cm bis Boden','20 cm to floor'),tr('10 cm bis Boden','10 cm to floor'),tr('5 cm bis Boden','5 cm to floor'),tr('Spagat erreicht','Split achieved')],middle:[tr('Breite Grätsche','Wide straddle'),tr('Unterarme am Boden','Forearms down'),tr('Becken unter Kniehöhe','Hips below knees'),tr('10 cm bis Boden','10 cm to floor'),tr('5 cm bis Boden','5 cm to floor'),tr('Seitspagat erreicht','Middle split achieved')],pancake:[tr('Aufrechter Sitz','Tall seated position'),tr('45° Vorbeuge','45° fold'),tr('Unterarme am Boden','Forearms down'),tr('Brust Richtung Boden','Chest toward floor'),tr('Flacher Rücken','Flat back'),tr('Pancake erreicht','Pancake achieved')],squat:[tr('Fersen unten','Heels down'),tr('90° Tiefe','90° depth'),tr('Ellbogen zwischen Knien','Elbows inside knees'),tr('Aufrechter Rücken','Upright spine'),tr('60 Sek. stabil','60 sec stable'),tr('Deep Squat gemeistert','Deep squat mastered')],overhead:[tr('Arme auf Ohrhöhe','Arms by ears'),tr('Rippen kontrolliert','Ribs controlled'),tr('180° Schulterflexion','180° shoulder flexion'),tr('Wall Line Hold','Wall line hold'),tr('30 Sek. Kontrolle','30 sec control'),tr('Overhead Freedom','Overhead freedom')]}[S.goal];const step=Math.min(milestones.length-1,Math.floor(S.score/(100/milestones.length)));return `<section class="journey-card"><p class="kicker">FLEXIBILITY JOURNEY</p><h2>${goalTitle(S.goal)}</h2><div class="journey-line">${milestones.map((m,i)=>`<span class="${i<=step?'done':''} ${i===step?'current':''}"><i>${i<step?'✓':i+1}</i><b>${m}</b></span>`).join('')}</div></section>`}
function weeklyReport(){const mins=Math.round((S.sessions*Math.max(8,S.lastSessionSeconds/60||18)));return `<section class="report-card"><div><p class="kicker">WEEKLY ARCHITECTURE REPORT</p><h2>${tr('Deine Woche in Zahlen','Your week in numbers')}</h2></div><div class="report-grid"><span><b>${S.sessions}</b>${tr('Sessions','Sessions')}</span><span><b>${mins}</b>${tr('Minuten','Minutes')}</span><span><b>${Math.min(100,S.sessions*8)}%</b>${tr('Konsistenz','Consistency')}</span><span><b>+${S.xp}</b>XP</span></div></section>`}

function planView(){const plan=buildPlan(),mins=Math.round(plan.reduce((a,e)=>a+e.sec,0)/60)+3;app.innerHTML=shell(`${backHeader(tr('Dein Trainingsplan','Your training plan'))}<section class="plan-summary"><div><p class="kicker">${S.level} · ${goalTitle(S.goal)}</p><h2>${tr('Heute: Zielgerichtete Mobility','Today: Goal-focused mobility')}</h2><p>${plan.length} ${tr('Übungen','exercises')} · ${mins} min</p></div><button class="btn gold" data-start>${tr('Plan starten','Start plan')}</button></section><div class="plan-list">${plan.map((e,i)=>`<article><b>${String(i+1).padStart(2,'0')}</b><img src="${imageFor(e)}" alt="${exn(e)}"><div><strong>${exn(e)}</strong><span>${e.area} · ${e.sec}s</span></div></article>`).join('')}</div>`,'plan')}
function blueprint(){const goalAreas=goals[S.goal].areas;const regions=[['shoulder',tr('Schultern','Shoulders')],['spine',tr('Wirbelsäule','Spine')],['hip',tr('Hüfte','Hips')],['hamstring',tr('Hamstrings','Hamstrings')],['adductor',tr('Adduktoren','Adductors')],['ankle',tr('Sprunggelenke','Ankles')]];return `<section class="blueprint"><div class="blueprint-copy"><p class="kicker">CRISPY FEATURE · STAS BLUEPRINT</p><h2>${tr('Deine Körper-Architektur','Your body architecture')}</h2><p>${tr('Die Zielzonen deines aktuellen Pfads leuchten gold. Nach jeder Session entwickelt sich dein Blueprint weiter.','Target zones for your current path glow gold. Your blueprint evolves after every session.')}</p><div class="region-grid">${regions.map(([k,n])=>`<span class="${goalAreas.includes(k)?'hot':''}"><i></i>${n}<b>${Math.min(100,goalAreas.includes(k)?S.score+12:Math.max(18,S.score-15))}%</b></span>`).join('')}</div></div><div class="body-map" aria-label="STAS Body Blueprint"><div class="head-dot"></div><div class="torso ${goalAreas.includes('spine')||goalAreas.includes('shoulder')?'hot':''}"></div><div class="arm left ${goalAreas.includes('shoulder')?'hot':''}"></div><div class="arm right ${goalAreas.includes('shoulder')?'hot':''}"></div><div class="pelvis ${goalAreas.includes('hip')||goalAreas.includes('adductor')?'hot':''}"></div><div class="leg left ${goalAreas.includes('hamstring')||goalAreas.includes('ankle')?'hot':''}"></div><div class="leg right ${goalAreas.includes('hamstring')||goalAreas.includes('ankle')?'hot':''}"></div></div></section>`}
function dailyChallenge(){const e=buildPlan()[Math.min(2,buildPlan().length-1)];return `<section class="daily-card ${S.dailyDone?'done':''}"><div><p class="kicker">DAILY ARCHITECTURE</p><h2>${S.dailyDone?tr('Challenge abgeschlossen','Challenge complete'):exn(e)}</h2><p>${S.dailyDone?tr('+10 Architecture XP gesichert.','+10 Architecture XP secured.'):tr('Halte die Position 60 Sekunden sauber und kontrolliert.','Hold the position cleanly and under control for 60 seconds.')}</p></div><button class="btn ${S.dailyDone?'ghost':'gold'}" data-daily ${S.dailyDone?'disabled':''}>${S.dailyDone?'✓ '+tr('Erledigt','Done'):tr('Challenge abschließen','Complete challenge')}</button></section>`}
function home(){const plan=buildPlan(),min=Math.round(plan.reduce((a,e)=>a+e.sec,0)/60)+3,l=xpLevel();app.innerHTML=shell(`<section class="hero"><div class="hero-copy"><p class="kicker">${tr('HEUTIGER ZIELPFAD','TODAY’S GOAL PATH')}</p><h1>${goalTitle(S.goal)}</h1><p>${goalDesc(S.goal)}</p><div class="goal-meter"><span style="width:${Math.max(8,S.score)}%"></span></div><small>${S.score}% ${tr('Zielerreichung','goal completion')}</small><div class="actions"><button class="btn gold" data-start>${tr('Session starten','Start session')} · ${min} min</button><button class="btn ghost" data-assess>${tr('Assessment','Assessment')}</button></div></div><div class="model-card ${S.sex}"><div class="model-symbol">${S.sex==='female'?'♀':'♂'}</div><img src="${imageFor(plan[0])}"><span>${tr('Ausgewähltes Modell','Selected model')}: ${S.sex==='female'?tr('Frau','Female'):tr('Mann','Male')}</span></div></section><section class="stats four"><article><b>${S.score}</b><span>STAS Score</span></article><article><b>${S.sessions}</b><span>${tr('Sessions','Sessions')}</span></article><article><b>${S.streak}</b><span>${tr('Tage Serie','Day streak')}</span></article><article><b>LV ${l.n}</b><span>${l.name} · ${l.pct}%</span></article></section>${coach()}${dailyChallenge()}${blueprint()}${journey()}<div class="section-title"><div><p class="kicker">${S.level}</p><h2>${tr('Dein heutiges Programm','Today’s program')}</h2></div><button data-go="library">${tr('Alle anzeigen','View all')} →</button></div><div class="cards">${plan.slice(0,4).map(card).join('')}</div>`,`start`)}
function card(e){return `<article class="ex-card"><div class="img-wrap"><img src="${imageFor(e)}" alt="${exn(e)}"><span>${e.sec}s</span></div><div><p class="kicker">${e.area}</p><h3>${exn(e)}</h3><small>${e.level}</small></div></article>`}
function library(){app.innerHTML=shell(`${backHeader(tr('Übungsbibliothek','Exercise library'))}<p class="kicker">32 ${tr('ÜBUNGEN','EXERCISES')}</p><div class="filters">${['all','hip','hamstring','adductor','ankle','shoulder','spine','core'].map(x=>`<button data-filter="${x}">${x}</button>`).join('')}</div><div class="cards" id="lib">${exercises.map(card).join('')}</div>`,'library')}
function progress(){const l=xpLevel();app.innerHTML=shell(`${backHeader(tr('Fortschritt','Progress'))}<p class="kicker">STAS ANALYTICS 4.0</p><section class="score-panel"><div class="ring" style="--p:${S.score}"><b>${S.score}</b><span>/100</span></div><div><h2>${goalTitle(S.goal)}</h2><p>${goalDesc(S.goal)}</p><div class="xp-track"><span style="width:${l.pct}%"></span></div><small>Level ${l.n} · ${l.name} · ${S.xp} XP</small><br><button class="btn gold" data-assess>${tr('Neues Assessment','New assessment')}</button></div></section>${mobilityDNA()}${journey()}${weeklyReport()}${coach()}`,'progress')}
function profile(){app.innerHTML=shell(`${backHeader(tr('Einstellungen','Settings'))}<p class="kicker">SETTINGS</p><div class="settings"><label>${tr('Modell','Model')}<select data-setting="sex"><option value="male" ${S.sex==='male'?'selected':''}>${tr('Mann','Male')}</option><option value="female" ${S.sex==='female'?'selected':''}>${tr('Frau','Female')}</option></select></label><label>Level<select data-setting="level">${['Beginner','Intermediate','Advanced','Elite'].map(x=>`<option ${S.level===x?'selected':''}>${x}</option>`).join('')}</select></label><label>${tr('Ziel','Goal')}<select data-setting="goal">${Object.entries(goals).map(([k,g])=>`<option value="${k}" ${S.goal===k?'selected':''}>${goalTitle(k)}</option>`).join('')}</select></label><label>${tr('Countdown-Ton','Countdown sound')}<select data-setting="sound"><option value="softBell" ${S.sound==='softBell'?'selected':''}>Soft Bell</option><option value="wood" ${S.sound==='wood'?'selected':''}>Wood Block</option><option value="chime" ${S.sound==='chime'?'selected':''}>Chime</option><option value="digital" ${S.sound==='digital'?'selected':''}>Digital Tick</option><option value="classic" ${S.sound==='classic'?'selected':''}>Classic Beep</option></select></label><label>${tr('Effektlautstärke','Effect volume')}<input type="range" min="0" max="1" step=".05" value="${S.effectsVolume}" data-effects></label><label class="toggle-row">${tr('Countdown-Ton aktiv','Countdown sound enabled')}<input type="checkbox" data-countdown ${S.countdownSound?'checked':''}></label><label class="toggle-row">${tr('Vibration aktiv','Vibration enabled')}<input type="checkbox" data-vibration ${S.vibration?'checked':''}></label><button class="btn ghost" data-preview>${tr('Ton testen','Preview sound')}</button><label>${tr('Musiklautstärke','Music volume')}<input type="range" min="0" max="1" step=".05" value="${S.volume}" data-volume></label><button class="btn ghost" data-reset>${tr('App zurücksetzen','Reset app')}</button></div>`,'profile')}
function startSession(){player.queue=buildPlan();player.index=0;player.phase='countdown';player.count=3;player.running=true;player.left=3;location.hash='session';startAudio();playCountdown('tick');player.last=performance.now();cancelAnimationFrame(player.raf);player.raf=requestAnimationFrame(loop);render()}
function loop(now){if(!player.running)return;const dt=(now-player.last)/1000;player.last=now;player.left-=dt;if(player.left<=0){if(player.phase==='countdown'){player.count--;if(player.count>0){player.left=1;playCountdown('tick')}else{player.phase='exercise';player.left=player.queue[player.index].sec;player.total=player.left;playCountdown('go')}}else{playCountdown('finish');nextExercise()}}updateTimer();player.raf=requestAnimationFrame(loop)}
function nextExercise(){if(player.index>=player.queue.length-1){finishSession();return}player.index++;player.phase='countdown';player.count=3;player.left=1;render()}
function updateTimer(){const n=document.querySelector('[data-time]'),ring=document.querySelector('.timer-ring');if(n)n.textContent=player.phase==='countdown'?player.count:Math.max(0,Math.ceil(player.left));if(ring){const pct=player.phase==='countdown'?100:(player.left/player.total*100);ring.style.setProperty('--time',pct)}}
function sessionView(){if(!player.queue.length){location.hash='start';return render()}const e=player.queue[player.index];app.innerHTML=`<div class="session with-nav"><header><button data-stop aria-label="${tr('Session schließen','Close session')}">×</button><div><span>${player.index+1} / ${player.queue.length}</span><div class="session-progress"><i style="width:${((player.index+1)/player.queue.length)*100}%"></i></div></div><button data-music>${audio.on?'♫':'♩'}</button></header><main><div class="session-image"><img src="${imageFor(e)}"><div class="sex-badge">${S.sex==='female'?'♀ '+tr('Frau','Female'):'♂ '+tr('Mann','Male')}</div></div><div class="session-info"><p class="kicker">${e.area} · ${e.level}</p><h1>${exn(e)}</h1><div class="timer-ring" style="--time:100"><b data-time>${player.phase==='countdown'?player.count:Math.ceil(player.left)}</b><span>${player.phase==='countdown'?tr('BEREIT','READY'):tr('SEKUNDEN','SECONDS')}</span></div><div class="tips">${e.tips.map(x=>`<span>✓ ${x}</span>`).join('')}</div><div class="controls"><button data-prev>‹</button><button class="play" data-pause>${player.running?'Ⅱ':'▶'}</button><button data-next>›</button></div><button class="session-home" data-stop>⌂ ${tr('Session beenden und zum Dashboard','End session and return to dashboard')}</button></div></main>${nav('session')}</div>`}
function finishSession(){player.running=false;cancelAnimationFrame(player.raf);stopAudio();const seconds=player.queue.reduce((a,e)=>a+e.sec,0)+player.queue.length*3;S.sessions++;S.streak=Math.max(1,S.streak+1);S.score=Math.min(100,S.score+Math.max(2,Math.round(12-S.sessions/3)));S.xp+=25;S.lastSessionSeconds=seconds;S.lastSessionExercises=player.queue.length;save();let auto=5;app.innerHTML=`<div class="finish"><p class="kicker">SESSION COMPLETE</p><h1>${tr('Stark abgeschlossen.','Strong finish.')}</h1><div class="ring" style="--p:${S.score}"><b>${S.score}</b><span>/100</span></div><div class="finish-stats"><span><b>${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}</b>${tr('Trainingszeit','Training time')}</span><span><b>${player.queue.length}</b>${tr('Übungen','Exercises')}</span><span><b>+25</b>Architecture XP</span><span><b>${S.streak}</b>${tr('Tage Streak','Day streak')}</span></div><button class="btn gold" data-finish>${tr('Zum Dashboard','Back to dashboard')}</button><p class="auto-home">${tr('Automatische Rückkehr in','Automatic return in')} <b data-auto>${auto}</b>s</p></div>`;const t=setInterval(()=>{auto--;const el=document.querySelector('[data-auto]');if(el)el.textContent=auto;if(auto<=0){clearInterval(t);location.hash='start';render()}},1000)}
function startAudio(){if(!S.music)return;try{audio.ctx ||= new (window.AudioContext||window.webkitAudioContext)();audio.master=audio.ctx.createGain();audio.master.gain.value=S.volume*.08;audio.master.connect(audio.ctx.destination);[110,164.81,220].forEach((f,i)=>{let o=audio.ctx.createOscillator(),g=audio.ctx.createGain();o.type=i?'sine':'triangle';o.frequency.value=f;g.gain.value=[.5,.18,.1][i];o.connect(g).connect(audio.master);o.start();audio.osc.push(o)});audio.on=true}catch(e){}}
function stopAudio(){audio.osc.forEach(o=>{try{o.stop()}catch(e){}});audio.osc=[];audio.on=false}
function tone(f,d,type='sine',gain=.12){try{audio.ctx ||= new (window.AudioContext||window.webkitAudioContext)();let o=audio.ctx.createOscillator(),g=audio.ctx.createGain();o.type=type;o.frequency.value=f;const v=Math.max(.001,gain*S.effectsVolume);g.gain.setValueAtTime(v,audio.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.ctx.currentTime+d);o.connect(g).connect(audio.ctx.destination);o.start();o.stop(audio.ctx.currentTime+d)}catch(e){}}
function playCountdown(stage='tick'){if(!S.countdownSound)return;const sounds={softBell:()=>{tone(stage==='go'?1046:880,.32,'sine',.16);setTimeout(()=>tone(stage==='go'?1568:1320,.22,'sine',.08),35)},wood:()=>tone(stage==='go'?360:260,.09,'square',.12),chime:()=>{tone(stage==='go'?1174:784,.24,'triangle',.12);setTimeout(()=>tone(stage==='go'?1760:1174,.2,'sine',.07),45)},digital:()=>tone(stage==='go'?980:700,.07,'square',.08),classic:()=>tone(stage==='go'?880:660,.12,'sine',.12)};(sounds[S.sound]||sounds.softBell)();if(S.vibration&&navigator.vibrate)navigator.vibrate(stage==='go'?[70,40,110]:35)}
function assessment(){const v=prompt(tr('Wie beweglich fühlst du dich heute? 1–10','How mobile do you feel today? 1–10'),'6');if(v){S.score=Math.max(10,Math.min(100,Number(v)*10));S.lastAssessment=Date.now();S.xp+=5;save();render()}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.lang!==undefined)set({lang:S.lang==='de'?'en':'de'});if(b.dataset.go){if(b.dataset.go==='start'){goHome();return}player.running=false;cancelAnimationFrame(player.raf);stopAudio();location.hash=b.dataset.go;render();return}if(b.hasAttribute('data-back')){history.length>1?history.back():(location.hash='start',render())}if(b.hasAttribute('data-daily')&&!S.dailyDone){S.dailyDone=true;S.score=Math.min(100,S.score+2);S.xp+=10;save();render()}if(b.dataset.sex)set({sex:b.dataset.sex});if(b.dataset.level)set({level:b.dataset.level});if(b.dataset.goal)set({goal:b.dataset.goal});if(b.hasAttribute('data-ob-next')){let s=Number(sessionStorage.getItem('obStep')||0);if(s<3){sessionStorage.setItem('obStep',++s);onboard(s)}else{S.onboarded=true;S.score=30;save();sessionStorage.removeItem('obStep');render()}}if(b.hasAttribute('data-ob-prev')){let s=Math.max(0,Number(sessionStorage.getItem('obStep')||0)-1);sessionStorage.setItem('obStep',s);onboard(s)}if(b.hasAttribute('data-enter')){S.onboarded=true;if(!S.score)S.score=30;save();location.hash='dashboard';render()}if(b.hasAttribute('data-dashboard')){location.hash='dashboard';render()}if(b.hasAttribute('data-start'))startSession();if(b.hasAttribute('data-assess'))assessment();if(b.hasAttribute('data-stop')){goHome();return}if(b.hasAttribute('data-pause')){player.running=!player.running;if(player.running){player.last=performance.now();player.raf=requestAnimationFrame(loop)}render()}if(b.hasAttribute('data-next'))nextExercise();if(b.hasAttribute('data-prev')&&player.index){player.index--;player.phase='countdown';player.count=3;player.left=1;render()}if(b.hasAttribute('data-music')){audio.on?stopAudio():startAudio();render()}if(b.hasAttribute('data-finish')){goHome();return}if(b.hasAttribute('data-preview'))playCountdown('go');if(b.hasAttribute('data-reset')){localStorage.removeItem('stas3');location.hash='start';location.reload()}if(b.dataset.filter){const f=b.dataset.filter;document.querySelector('#lib').innerHTML=exercises.filter(x=>f==='all'||x.area===f).map(card).join('')}});
document.addEventListener('change',e=>{if(e.target.dataset.setting)set({[e.target.dataset.setting]:e.target.value});if(e.target.hasAttribute('data-volume'))set({volume:Number(e.target.value)});if(e.target.hasAttribute('data-effects'))set({effectsVolume:Number(e.target.value)});if(e.target.hasAttribute('data-countdown'))set({countdownSound:e.target.checked});if(e.target.hasAttribute('data-vibration'))set({vibration:e.target.checked})});window.addEventListener('hashchange',render);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=410');if(location.hash!=='#session')history.replaceState(null,'',location.pathname+location.search+'#start');render();
