const exercises=[
 {id:'squat',img:'01-deep-squat.webp',de:'Tiefe Hocke',en:'Deep Squat Hold',block:'A',sec:30,reps:'30 Sek.',tips:['Fersen am Boden halten','Knie aktiv nach außen führen','Wirbelsäule lang halten']},
 {id:'couch',img:'02-couch-stretch.webp',de:'Couch Stretch',en:'Couch Stretch',block:'A',sec:45,reps:'30 Sek. pro Seite',tips:['Becken leicht einrollen','Gesäß der hinteren Seite anspannen','Nicht ins Hohlkreuz ausweichen']},
 {id:'catcow',img:'03-cat-cow.webp',de:'Katze–Kuh',en:'Cat–Cow',block:'A',sec:45,reps:'6 Wiederholungen',tips:['Bewegung segmentweise führen','Ruhig durch die Nase atmen','Schultern weg von den Ohren']},
 {id:'bridge',img:'04-glute-bridge.webp',de:'Glute Bridge',en:'Glute Bridge',block:'B',sec:45,reps:'12 Wiederholungen',tips:['Fersen in den Boden drücken','Rippen unten halten','Oben das Gesäß anspannen']},
 {id:'deadbug',img:'05-dead-bug.webp',de:'Dead Bug',en:'Dead Bug',block:'B',sec:50,reps:'10 pro Seite',tips:['Lendenwirbelsäule am Boden','Langsam diagonal strecken','Ausatmen beim Absenken']},
 {id:'sideplank',img:'06-side-plank.webp',de:'Seitstütz',en:'Side Plank',block:'B',sec:40,reps:'30 Sek. pro Seite',tips:['Körper in einer Linie','Unterarm aktiv wegdrücken','Becken nicht absinken lassen']},
 {id:'hipswitch',img:'07-hip-switch.webp',de:'90/90 Hüftwechsel',en:'90/90 Hip Switch',block:'C',sec:55,reps:'8 pro Seite',tips:['Sitzbeinhöcker kontrolliert belasten','Knie ohne Schwung wechseln','Brustbein aufrichten']},
 {id:'wgs',img:'08-worlds-greatest-stretch.webp',de:'World’s Greatest Stretch',en:'World’s Greatest Stretch',block:'C',sec:50,reps:'8 pro Seite',tips:['Vorderes Knie über dem Fuß','Hinteres Bein lang','Rotation aus der Brustwirbelsäule']},
 {id:'thoracic',img:'09-thoracic-rotation.webp',de:'Brustwirbelsäulen-Rotation',en:'Thoracic Rotation',block:'C',sec:45,reps:'8 pro Seite',tips:['Becken stabil halten','Arm zur Decke führen','Blick folgt der Hand']},
 {id:'sweep',img:'10-hamstring-sweep.webp',de:'Hamstring Sweep',en:'Hamstring Sweep',block:'D',sec:45,reps:'8 pro Seite',tips:['Standbein weich','Hüfte nach hinten schieben','Rücken neutral halten']},
 {id:'lunge',img:'11-lunge-with-twist.webp',de:'Ausfallschritt mit Rotation',en:'Lunge with Twist',block:'D',sec:50,reps:'8 pro Seite',tips:['Stabilen Ausfallschritt halten','Becken gerade ausrichten','Kontrolliert rotieren']}
];
const blocks={A:{de:'Fundament',en:'Foundation'},B:{de:'Stabilität',en:'Stability'},C:{de:'Mobilität',en:'Mobility'},D:{de:'Integration',en:'Integration'}};
const i18n={
 de:{home:'Home',assessment:'Assessment',training:'Training',progress:'Fortschritt',profile:'Mehr',welcome:'Willkommen zurück!',ready:'Bereit, deine Beweglichkeit auf das nächste Level zu bringen?',startAssessment:'Assessment starten',startTraining:'Training starten',today:'Dein heutiger Fokus',program:'Trainingsprogramm',tests:'5 Tests · ca. 5 Minuten',score:'Bewegungsscore',sessions:'Sessions',streak:'Serie',exercises:'Übungen',allExercises:'Alle Übungen',start30:'30-Minuten-Session starten',back:'Zurück',next:'Weiter',pause:'Pause',resume:'Fortsetzen',skip:'Überspringen',remaining:'verbleibend',current:'Aktuelle Übung',nextExercise:'Nächste Übung',good:'Korrekt',adjust:'Anpassen',regress:'Zurückstufen',complete:'Session abgeschlossen',save:'Ergebnis speichern',install:'App installieren',installText:'Öffne die Seite über HTTPS. Auf iPhone: Teilen → Zum Home-Bildschirm. Auf Android: Browsermenü → App installieren.',reset:'Fortschritt zurücksetzen'},
 en:{home:'Home',assessment:'Assessment',training:'Training',progress:'Progress',profile:'More',welcome:'Welcome back!',ready:'Ready to take your mobility to the next level?',startAssessment:'Start assessment',startTraining:'Start training',today:'Today’s focus',program:'Training program',tests:'5 tests · about 5 minutes',score:'Mobility score',sessions:'Sessions',streak:'Streak',exercises:'Exercises',allExercises:'All exercises',start30:'Start 30-minute session',back:'Back',next:'Next',pause:'Pause',resume:'Resume',skip:'Skip',remaining:'remaining',current:'Current exercise',nextExercise:'Next exercise',good:'Correct',adjust:'Adjust',regress:'Regress',complete:'Session complete',save:'Save result',install:'Install app',installText:'Open this page over HTTPS. On iPhone: Share → Add to Home Screen. On Android: browser menu → Install app.',reset:'Reset progress'}
};
const state={view:'home',lang:localStorage.getItem('stasLang')||'de',assessment:JSON.parse(localStorage.getItem('stasAssessment')||'[0,0,0,0,0]'),index:0,queue:[],remaining:0,running:false,timer:null};
const $=s=>document.querySelector(s),t=k=>i18n[state.lang][k],name=e=>e[state.lang];
const asset=path=>new URL(path,document.baseURI).href;
function saved(){return JSON.parse(localStorage.getItem('stasProgress')||'{"sessions":0,"streak":0,"ratings":{},"last":null}')}
function storeProgress(p){localStorage.setItem('stasProgress',JSON.stringify(p))}
function shell(content){return `<div class="app-shell"><header class="topbar"><div class="brand">STAS</div><div class="top-actions"><button class="lang-btn" data-action="lang">${state.lang.toUpperCase()}</button><button class="icon-btn" data-view="profile">☰</button></div></header><main class="screen">${content}</main>${nav()}</div>`}
function nav(){const items=[['home','⌂','home'],['assessment','◉','assessment'],['training','✦','training'],['progress','▥','progress'],['profile','○','profile']];return `<nav class="bottom-nav">${items.map(([v,ic,k])=>`<button class="nav-btn ${state.view===v?'active':''}" data-view="${v}"><span>${ic}</span>${t(k)}</button>`).join('')}</nav>`}
function home(){const p=saved(),score=assessmentScore();return shell(`<section class="welcome"><div><div class="eyebrow">Science · Technology · Athletic · Systems</div><h1>${t('welcome')}</h1><p>${t('ready')}</p></div><div class="score-ring"><strong>${score}</strong><span>/100</span></div></section><div class="stats"><div class="stat"><strong>${score}</strong><span>${t('score')}</span></div><div class="stat"><strong>${p.sessions}</strong><span>${t('sessions')}</span></div><div class="stat"><strong>${p.streak}</strong><span>${t('streak')}</span></div></div><section class="dashboard-grid"><article class="card action-card assessment-action"><div><div class="eyebrow">Mobility Assessment</div><h2>${state.lang==='de'?'Teste deine Beweglichkeit':'Test your mobility'}</h2><p>${t('tests')}</p><button class="btn btn-primary" data-view="assessment">${t('startAssessment')}</button></div><img src="${asset('assets/hero.webp')}" alt="Mobility assessment"></article><article class="card action-card training-action"><div><div class="eyebrow">${t('program')}</div><h2>Foundation Flow</h2><p>4 Blocks · 11 ${t('exercises')} · 30 Min.</p><button class="btn btn-primary" data-action="start-full">${t('startTraining')}</button></div><img src="${asset('assets/exercises/08-worlds-greatest-stretch.webp')}" alt="Training"></article></section><div class="section-head"><div><div class="eyebrow">${t('today')}</div><h2>Foundation Flow</h2></div><button data-view="training">${t('allExercises')} →</button></div><div class="grid">${exercises.slice(0,3).map(exCard).join('')}</div>`)}
function exCard(e){return `<article class="card exercise-card" data-exercise="${e.id}"><img src="${asset(`assets/exercises/${e.img}`)}" alt="${name(e)}"><div class="exercise-body"><div class="eyebrow">Block ${e.block}</div><div class="row"><h3>${name(e)}</h3><span>›</span></div><div class="meta">${e.reps}</div></div></article>`}
function assessmentScore(){const valid=state.assessment.filter(Boolean);return valid.length?Math.round(valid.reduce((a,b)=>a+b,0)/(valid.length*5)*100):0}
function assessment(){const tests=state.lang==='de'?['Tiefe Hocke','Hüftbeuger','Rotation','Schulter','Hamstrings']:['Deep squat','Hip flexor','Rotation','Shoulder','Hamstrings'];return shell(`<div class="eyebrow">Mobility</div><h1 class="page-title">${t('assessment')}</h1><p class="sub">${t('tests')}</p><div class="assessment-list">${tests.map((x,i)=>`<article class="card assessment-card"><div class="badge">${i+1}</div><div><strong>${x}</strong><div class="meta">${state.lang==='de'?'Bewerte deine Kontrolle von 1 bis 5':'Rate your control from 1 to 5'}</div><div class="score-control">${[1,2,3,4,5].map(n=>`<button class="${state.assessment[i]===n?'active':''}" data-score="${i}:${n}">${n}</button>`).join('')}</div></div><span>›</span></article>`).join('')}</div><div class="card result"><div class="eyebrow">${t('score')}</div><strong>${assessmentScore()}</strong><div>/100</div><div class="cta-row" style="justify-content:center"><button class="btn btn-primary" data-action="save-assessment">${t('save')}</button></div></div>`)}
function training(){return shell(`<div class="eyebrow">4 Blocks · 11 ${t('exercises')}</div><h1 class="page-title">${t('program')}</h1><p class="sub">30 Minuten · Ganzkörper · Level 2</p><div class="assessment-list">${Object.entries(blocks).map(([key,b])=>{const list=exercises.filter(e=>e.block===key);return `<article class="card program-card"><div class="badge">${key}</div><div style="flex:1"><div class="eyebrow">Block ${key}</div><h3>${b[state.lang]}</h3><div class="meta">${list.length} ${t('exercises')} · ${Math.round(list.reduce((a,e)=>a+e.sec,0)/60)} Min.</div></div><button class="icon-btn" data-action="start-block" data-block="${key}">▶</button></article>`}).join('')}</div><div class="cta-row"><button class="btn btn-primary" data-action="start-full">${t('start30')}</button></div><div class="section-head"><h2>${t('allExercises')}</h2></div><div class="grid">${exercises.map(exCard).join('')}</div>`)}
function progress(){const p=saved();return shell(`<div class="eyebrow">STAS Analytics</div><h1 class="page-title">${t('progress')}</h1><div class="stats"><div class="stat"><strong>${p.sessions}</strong><span>${t('sessions')}</span></div><div class="stat"><strong>${p.streak}</strong><span>${t('streak')}</span></div><div class="stat"><strong>${assessmentScore()}</strong><span>${t('score')} / 100</span></div></div><div class="card" style="padding:22px"><h2>${state.lang==='de'?'Technikbewertungen':'Technique ratings'}</h2>${Object.keys(p.ratings).length?Object.entries(p.ratings).map(([id,r])=>{const e=exercises.find(x=>x.id===id);return `<div class="program-card" style="padding:12px 0;border-bottom:1px solid #292929"><strong>${e?name(e):id}</strong><span class="meta">${r}</span></div>`}).join(''):`<div class="empty">${state.lang==='de'?'Noch keine Bewertungen gespeichert.':'No ratings saved yet.'}</div>`}<div class="cta-row"><button class="btn btn-secondary" data-action="reset">${t('reset')}</button></div></div>`)}
function profile(){return shell(`<div class="eyebrow">STAS 2.0</div><h1 class="page-title">${t('profile')}</h1><div class="card" style="padding:22px"><h2>${t('install')}</h2><p class="install-note">${t('installText')}</p><button class="btn btn-primary" data-action="install">${t('install')}</button></div><div class="card" style="padding:22px;margin-top:14px"><h2>Sprache / Language</h2><div class="cta-row"><button class="btn ${state.lang==='de'?'btn-primary':'btn-secondary'}" data-setlang="de">Deutsch</button><button class="btn ${state.lang==='en'?'btn-primary':'btn-secondary'}" data-setlang="en">English</button></div></div>`)}
function startSession(queue){clearInterval(state.timer);state.queue=queue;state.index=0;state.remaining=queue[0].sec;state.running=false;state.view='session';render()}
function session(){const e=state.queue[state.index],next=state.queue[state.index+1],pct=(1-state.remaining/e.sec)*100;return shell(`<div class="eyebrow">${state.index+1} / ${state.queue.length}</div><h1 class="page-title">30-Minuten-Session</h1><div class="session"><div class="card session-media"><img src="${asset(`assets/exercises/${e.img}`)}" alt="${name(e)}"><div class="session-overlay"><div class="timer">${formatTime(state.remaining)}</div><div class="meta">${t('remaining')}</div><div class="progress-track" style="margin-top:12px"><div class="progress-fill" style="width:${pct}%"></div></div></div></div><aside class="card session-side"><div class="eyebrow">${t('current')} · Block ${e.block}</div><h2>${name(e)}</h2><div class="meta">${e.reps}</div><div class="tips">${e.tips.map(x=>`<div class="tip">✓ ${x}</div>`).join('')}</div>${next?`<div class="meta">${t('nextExercise')}</div><strong>${name(next)}</strong>`:''}<div class="session-controls" style="margin-top:20px"><button class="btn btn-secondary" data-action="prev">‹ ${t('back')}</button><button class="btn btn-primary primary" data-action="toggle">${state.running?'Ⅱ '+t('pause'):'▶ '+t('resume')}</button><button class="btn btn-secondary" data-action="next">${t('skip')} ›</button></div><div class="rating"><button data-rate="${t('good')}">✓ ${t('good')}</button><button data-rate="${t('adjust')}">! ${t('adjust')}</button><button data-rate="${t('regress')}">↘ ${t('regress')}</button></div></aside></div>`)}
function finish(){clearInterval(state.timer);const p=saved();p.sessions+=1;p.streak+=1;p.last=new Date().toISOString();storeProgress(p);state.running=false;state.view='progress';render();toast(t('complete'))}
function tick(){if(!state.running)return;state.remaining-=1;if(state.remaining<=0){if(state.index>=state.queue.length-1){finish();return}state.index++;state.remaining=state.queue[state.index].sec}render()}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function render(){let html=state.view==='home'?home():state.view==='assessment'?assessment():state.view==='training'?training():state.view==='progress'?progress():state.view==='profile'?profile():session();$('#app').innerHTML=html;window.scrollTo({top:0,behavior:'instant'})}
function toast(msg){const n=document.createElement('div');n.className='toast';n.textContent=msg;document.body.append(n);setTimeout(()=>n.remove(),1800)}
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-exercise]');if(!b)return;if(b.dataset.view){clearInterval(state.timer);state.running=false;state.view=b.dataset.view;render();return}if(b.dataset.exercise){startSession([exercises.find(x=>x.id===b.dataset.exercise)]);return}if(b.dataset.score){const [i,n]=b.dataset.score.split(':').map(Number);state.assessment[i]=n;render();return}if(b.dataset.setlang){state.lang=b.dataset.setlang;localStorage.setItem('stasLang',state.lang);render();return}const a=b.dataset.action;if(a==='lang'){state.lang=state.lang==='de'?'en':'de';localStorage.setItem('stasLang',state.lang);render()}if(a==='save-assessment'){localStorage.setItem('stasAssessment',JSON.stringify(state.assessment));toast(state.lang==='de'?'Assessment gespeichert':'Assessment saved')}if(a==='start-full')startSession([...exercises]);if(a==='start-block')startSession(exercises.filter(x=>x.block===b.dataset.block));if(a==='toggle'){state.running=!state.running;if(state.running&&!state.timer)state.timer=setInterval(tick,1000);render()}if(a==='next'){if(state.index<state.queue.length-1){state.index++;state.remaining=state.queue[state.index].sec;render()}else finish()}if(a==='prev'){if(state.index>0){state.index--;state.remaining=state.queue[state.index].sec;render()}}if(a==='reset'){localStorage.removeItem('stasProgress');localStorage.removeItem('stasAssessment');state.assessment=[0,0,0,0,0];render();toast(state.lang==='de'?'Zurückgesetzt':'Reset')}if(a==='install'){deferredPrompt?deferredPrompt.prompt():toast(state.lang==='de'?'Browsermenü verwenden':'Use browser menu')}if(b.dataset.rate){const p=saved(),ex=state.queue[state.index];p.ratings[ex.id]=b.dataset.rate;storeProgress(p);toast(b.dataset.rate)}});
if('serviceWorker' in navigator)window.addEventListener('load',async()=>{try{const regs=await navigator.serviceWorker.getRegistrations();for(const reg of regs){if(reg.active&&reg.active.scriptURL&&!reg.active.scriptURL.includes('sw.js?v=210'))await reg.unregister()}await navigator.serviceWorker.register('./sw.js?v=210',{scope:'./'});}catch(e){console.warn('Service worker:',e)}});
render();
